"""Deterministyczne tworzenie kodu wyłącznie ze zwalidowanych akcji."""

import json
from datetime import datetime
from pathlib import Path

from .plan_schema import PlanValidator


class ScriptBuilder:
    def build(self, plan):
        result = PlanValidator().validate(plan)
        if not result.runnable:
            raise ValueError("Nie można utworzyć skryptu z niekompletnego lub błędnego planu.")
        lines = ["# Generated by APP v2 ScriptBuilder; do not edit.",
                 "def run(actions, stop_event=None):"]
        for step in plan["steps"]:
            lines.extend(["    if stop_event is not None and stop_event.is_set():", "        return"])
            args = ", ".join(f"{key}={value!r}" for key, value in sorted(step["args"].items()))
            lines.append(f"    actions.{step['action']}({args})")
        return "\n".join(lines) + "\n"

    def save(self, root, request, plan, llm_response=None):
        root = Path(root)
        root.mkdir(parents=True, exist_ok=True)
        directory = root / datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        suffix = 1
        while True:
            try:
                directory.mkdir()
                break
            except FileExistsError:
                directory = root / f"{datetime.now():%Y-%m-%d_%H-%M-%S}_{suffix:02d}"
                suffix += 1
        (directory / "request.txt").write_text(request, encoding="utf-8")
        (directory / "plan.json").write_text(json.dumps(plan, ensure_ascii=False, indent=2), encoding="utf-8")
        if llm_response is not None:
            (directory / "llm_response.json").write_text(llm_response, encoding="utf-8")
        (directory / "run.log").touch()
        if PlanValidator().validate(plan).runnable:
            (directory / "script.py").write_text(self.build(plan), encoding="utf-8")
        return directory
